[package]
name = "cam_ascii"
version = "0.1.0"
edition = "2024"

[dependencies]
nokhwa = { version = "0.10", features = ["input-native"] }
image = "0.25"
anyhow = "1.0"
crossterm = "0.26"
rayon = "1.7"
crossbeam-channel = "0.5"
